// ! DO NOT EDIT THIS FILE BY HAND !
// File is generated from running wallet-extension/bin/generate-api-skeleton.py
// If this code needs to change, change the generation script.
//
// Needs to be generated manually. At repository root run:
// `python wallet-extension/bin/generate-api-skeleton.py`
//
// The naming of the API methods follows the Ethereum JSON-RPC convention.
// [See the current list of methods here.](https://eth.wiki/json-rpc/API#json-rpc-methods)

/* eslint-disable camelcase */
import log from 'loglevel';

import eth_accounts from './eth_accounts';
import eth_call from './eth_call';
import eth_getBalance from './eth_getBalance';
import eth_sendTransaction from './eth_sendTransaction';
import eth_sign from './eth_sign';

interface Message {
    data: {
        id: number;
        jsonrpc: string;
        method: string;
        params: Record<string, unknown>;
    };
    name: string;
}

export default function runApi(msg: Message): void {
    switch (msg.data.method) {
        case 'eth_accounts':
            eth_accounts(msg.data.params);
            break;
        case 'eth_call':
            eth_call(msg.data.params);
            break;
        case 'eth_getBalance':
            eth_getBalance(msg.data.params);
            break;
        case 'eth_sendTransaction':
            eth_sendTransaction(msg.data.params);
            break;
        case 'eth_sign':
            eth_sign(msg.data.params);
            break;
        default:
            log.error(`wallet: ${msg.data.method} method is not recognized.`);
            break;
    }
}
